### ISSUE TITLE
Client crash when Give Weapon's sm_gimme command is used

### ISSUE THREAD

**Issue by MrPanica** [nosoop/SM-TFEconDataCompat#3]
I don’t know, maybe it’s not provided.
If you give yourself some weapons, for example 15000 Night Owl or 1190 Second Banana, then your game will crash.

I tried this on a clean server.

```
L 04/25/2021 - 23:59:02: [tf2items_giveweapon.smx] "Hot<9><[U:1:149724700]><>" gave weapon 15000 to self
STEAMAUTH: Client Hot received failure code 6
STEAMAUTH: Client Hot received failure code 6
RecordSteamInterfaceCreation (PID 26084): SteamGameStats001 / 
RecordSteamInterfaceCreation (PID 26084): SteamGameStats001 / 
Dropped Hot from server (Client left game (Steam auth ticket has been canceled)
)
Server is hibernating
```

**Comment by nosoop** [comment]
It's more of an issue with older plugins assuming that attributes would always be runtime-applicable; that changed with one of the recent major updates that introduced minmode viewmodels, which added string attributes to every weapon, which aren't synchronized directly between the client / server.  I feel like it should be fixed there.

There shouldn't be any need to copy schema / static attributes anyways, since they're already defined statically (TF2Items' `PRESERVE_ATTRIBUTES` flag or the `m_bOnlyIterateItemViewAttributes` networked property would get things half working, then removing the functionality that reads static attributes from the plugin would be the other half).

It's definitely something I've been iffy about for a while; see #1.

@FlaminSarge any input on this?

**Comment by FlaminSarge** [comment]
Static attributes weren't a thing when some of the original stuff was written, better to adapt GiveWeapon/etc. to assume static attributes are present and not try to set them, instead of what it currently does. Half of GiveWeapon's stuff could be removed and then a feature added for 'no_static_attrs' or something in custom weapons, really.

GiveWeapon as a plugin sitting on top of New Randomizer would be neat, too.

**Comment by mku4eHnSaWAZbK** [comment]
When `tf_use_min_viewmodels 1`, I crash. When `tf_use_min_viewmodels 0`, crashes stopped immediately. When I used TF2 Give Weapons with TF2IDB, the weapon would be given with large viewmodels while everything else is using min. Same crash message. Could be related.

**Comment by nosoop** [comment]
From a now-deleted comment (account, even):

> When `tf_use_min_viewmodels 1`, I crash. When `tf_use_min_viewmodels 0`, crashes stopped immediately. When I used TF2 Give Weapons with TF2IDB, the weapon would be given with large viewmodels while everything else is using min. Same crash message. Could be related.

Yeah &mdash; the client is reading the `min_viewmodel_offset` attribute that was networked by GiveWeapon when it shouldn't be (it's a string that isn't replicated across the network, so the client crashes because it's performing an invalid memory access).  The compatibility shim is simply reporting what it sees, which is why I consider this a 'wontfix' on this plugin.

There are different two solutions to this:

- Have Valve introduce client-specific code that skips checking runtime values if they're not supported based on `ISchemaAttributeType::BSupportsGameplayModificationAndNetworking()`
- Modify Give Weapon to not copy static attributes and ensure that the game's native static attribute iteration is enabled (see my original reply on this issue).

**Comment by mku4eHnSaWAZbK** [comment]
oh yeah my bad i didnt your reply mentioning min viewmodels
